const express = require('express')
const router = express.Router()
const dashboardController = require('../app/controller/DashboardController')
const employeesRouter = express.Router()
const managersRouter = express.Router()

// Use the nested routers
router.use('/employees', employeesRouter)
router.use('/managers', managersRouter)

// Employee routes
employeesRouter.get('/', dashboardController.employees_overview)
employeesRouter.get('/overview', dashboardController.employees_overview)
employeesRouter.get('/dashboard', dashboardController.employees_dashboard)
employeesRouter.get('/notes', dashboardController.employees_notes)
employeesRouter.get('/product', dashboardController.employees_products)
employeesRouter.get('/setting', dashboardController.employees_settings)
employeesRouter.get('/order', dashboardController.employees_orders)
employeesRouter.get('/changeinfo', dashboardController.employees_changeinfo)
// employeesRouter.get('/feedback', dashboardController.employees_feedback)
employeesRouter.put('/orders/:id', dashboardController.employees_ordersdelivered)
// employeesRouter.get('/changeinfo/:id', dashboardController.employees_editinfo)
employeesRouter.put('/changeinfo/:id', dashboardController.employees_updateinfo)

// Manager routes
managersRouter.get('/', dashboardController.managers_overview)
managersRouter.get('/overview', dashboardController.managers_overview)
managersRouter.get('/dashboard', dashboardController.managers_dashboard)
managersRouter.get('/staff', dashboardController.managers_staffs)
managersRouter.get('/customer', dashboardController.managers_customers)
managersRouter.get('/note', dashboardController.managers_notes)
managersRouter.get('/product', dashboardController.managers_products)
managersRouter.get('/setting', dashboardController.managers_settings)
managersRouter.get('/orders', dashboardController.managers_orders)
managersRouter.delete('/staff/:id', dashboardController.managers_deletestaffs)
managersRouter.delete('/customer/:id', dashboardController.managers_deletecustomers)
managersRouter.delete('/product/:id', dashboardController.managers_deleteproducts)
managersRouter.delete('/note/:id', dashboardController.managers_deletenotes)
// managersRouter.put('/orders/:id', dashboardController.managers_ordersdeclined)
// managersRouter.post('/store', dashboardController.managers_store)
// managersRouter.post('/storenotes', dashboardController.managers_storenotes)
// managersRouter.post('/storeproducts', dashboardController.managers_storeproducts)
// managersRouter.get('/changeinfo/:id', dashboardController.managers_editinfo)
managersRouter.put('/changeinfo/:id', dashboardController.managers_updateinfo)
// managersRouter.get('/feedback', dashboardController.managers_feedback)
managersRouter.get('/:id', dashboardController.managers_editstaffs)
managersRouter.put('/:id', dashboardController.managers_updatestaffs)

module.exports = router
